import type { Session } from "./types";

export const mockSessions: Session[] = [
  {
    id: "sess-001",
    workspaceId: "ws-001",
    name: "proj-auth",
    status: "active",
    currentAgent: "tapestry",
    initialPrompt: "Implement JWT authentication module with refresh tokens",
    source: { type: "pipeline", pipelineId: "pipe-001", stageIndex: 1 },
    tokens: { input: 24200, output: 9800, reasoning: 4200, cache: 12400 },
    cost: 1.2,
    contextUsage: 0.34,
    planRef: ".weave/plans/auth-module.md",
    planProgress: { done: 4, total: 7 },
    pipelineStageId: "stage-002",
    tags: ["auth", "backend"],
    modifiedFiles: [
      { path: "src/auth/auth.model.ts", type: "added" },
      { path: "src/auth/auth.service.ts", type: "added" },
      { path: "src/auth/auth.middleware.ts", type: "added" },
      { path: "prisma/schema.prisma", type: "modified" },
    ],
    createdAt: new Date("2026-02-27T10:30:00"),
  },
  {
    id: "sess-002",
    workspaceId: "ws-002",
    name: "proj-payments",
    status: "active",
    currentAgent: "loom",
    initialPrompt: "Analyze the payment processing flow and identify bottlenecks",
    source: { type: "manual" },
    tokens: { input: 8400, output: 3600, reasoning: 1800, cache: 4200 },
    cost: 0.45,
    contextUsage: 0.12,
    tags: ["payments", "analysis"],
    modifiedFiles: [],
    createdAt: new Date("2026-02-27T10:42:00"),
  },
  {
    id: "sess-003",
    workspaceId: "ws-003",
    name: "proj-api",
    status: "active",
    currentAgent: "shuttle",
    initialPrompt: "Build REST API endpoints for user management",
    source: { type: "template", templateId: "tpl-001" },
    tokens: { input: 5600, output: 2400, reasoning: 800, cache: 2800 },
    cost: 0.3,
    contextUsage: 0.08,
    planRef: ".weave/plans/api-endpoints.md",
    planProgress: { done: 1, total: 5 },
    tags: ["api", "backend"],
    modifiedFiles: [
      { path: "src/api/users.controller.ts", type: "added" },
    ],
    createdAt: new Date("2026-02-27T10:45:00"),
  },
  {
    id: "sess-004",
    workspaceId: "ws-004",
    name: "proj-docs",
    status: "idle",
    currentAgent: "loom",
    initialPrompt: "Generate API documentation from the codebase",
    source: { type: "batch", batchId: "batch-001" },
    tokens: { input: 38000, output: 14000, reasoning: 6000, cache: 18000 },
    cost: 1.85,
    contextUsage: 0.52,
    tags: ["docs"],
    modifiedFiles: [
      { path: "docs/api-reference.md", type: "added" },
      { path: "docs/getting-started.md", type: "added" },
    ],
    createdAt: new Date("2026-02-27T09:15:00"),
  },
  {
    id: "sess-005",
    workspaceId: "ws-005",
    name: "proj-tests",
    status: "active",
    currentAgent: "tapestry",
    initialPrompt: "Write integration tests for the payment module",
    source: { type: "github", issueUrl: "https://github.com/org/repo/issues/42", issueNumber: 42 },
    tokens: { input: 12800, output: 5200, reasoning: 2600, cache: 6400 },
    cost: 0.68,
    contextUsage: 0.18,
    planRef: ".weave/plans/payment-tests.md",
    planProgress: { done: 2, total: 4 },
    tags: ["tests", "payments"],
    modifiedFiles: [
      { path: "tests/payment.integration.test.ts", type: "added" },
      { path: "tests/fixtures/payment.fixture.ts", type: "added" },
    ],
    createdAt: new Date("2026-02-27T10:20:00"),
  },
  {
    id: "sess-006",
    workspaceId: "ws-006",
    name: "proj-refactor",
    status: "completed",
    currentAgent: "loom",
    initialPrompt: "Refactor the database connection pool to use singleton pattern",
    source: { type: "manual" },
    tokens: { input: 42000, output: 18000, reasoning: 8000, cache: 21000 },
    cost: 2.15,
    contextUsage: 0.0,
    tags: ["refactor", "database"],
    modifiedFiles: [
      { path: "src/db/connection.ts", type: "modified" },
      { path: "src/db/pool.ts", type: "modified" },
      { path: "src/db/index.ts", type: "modified" },
    ],
    createdAt: new Date("2026-02-27T08:00:00"),
    completedAt: new Date("2026-02-27T08:45:00"),
  },
  {
    id: "sess-007",
    workspaceId: "ws-007",
    name: "proj-ci",
    status: "error",
    currentAgent: "tapestry",
    initialPrompt: "Set up GitHub Actions CI/CD pipeline",
    source: { type: "manual" },
    tokens: { input: 15000, output: 6000, reasoning: 3000, cache: 7500 },
    cost: 0.78,
    contextUsage: 0.21,
    tags: ["ci", "devops"],
    modifiedFiles: [
      { path: ".github/workflows/ci.yml", type: "added" },
    ],
    createdAt: new Date("2026-02-27T09:30:00"),
  },
  {
    id: "sess-008",
    workspaceId: "ws-008",
    name: "proj-frontend",
    status: "waiting_input",
    currentAgent: "loom",
    initialPrompt: "Build the settings page with dark mode toggle",
    source: { type: "template", templateId: "tpl-002" },
    tokens: { input: 22000, output: 9000, reasoning: 4000, cache: 11000 },
    cost: 1.12,
    contextUsage: 0.31,
    planRef: ".weave/plans/settings-page.md",
    planProgress: { done: 3, total: 6 },
    tags: ["frontend", "ui"],
    modifiedFiles: [
      { path: "src/pages/settings.tsx", type: "added" },
      { path: "src/components/theme-toggle.tsx", type: "added" },
      { path: "src/styles/theme.css", type: "added" },
    ],
    createdAt: new Date("2026-02-27T10:00:00"),
  },
];
