/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsV1RouteImport } from './routes/sessions-v1'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GithubRouteImport } from './routes/github'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIdRouteImport } from './routes/sessions.$id'
import { Route as SessionsV1IdRouteImport } from './routes/sessions-v1_.$id'
import { Route as SettingsPluginsPluginIdRouteImport } from './routes/settings_.plugins.$pluginId'
import { Route as GithubOwnerRepoRouteImport } from './routes/github.$owner.$repo'
import { Route as GithubOwnerRepoPullsNumberRouteImport } from './routes/github.$owner.$repo.pulls.$number'
import { Route as GithubOwnerRepoIssuesNumberRouteImport } from './routes/github.$owner.$repo.issues.$number'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsV1Route = SessionsV1RouteImport.update({
  id: '/sessions-v1',
  path: '/sessions-v1',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsV1IdRoute = SessionsV1IdRouteImport.update({
  id: '/sessions-v1_/$id',
  path: '/sessions-v1/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPluginsPluginIdRoute = SettingsPluginsPluginIdRouteImport.update({
  id: '/settings_/plugins/$pluginId',
  path: '/settings/plugins/$pluginId',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubOwnerRepoRoute = GithubOwnerRepoRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => GithubRoute,
} as any)
const GithubOwnerRepoPullsNumberRoute =
  GithubOwnerRepoPullsNumberRouteImport.update({
    id: '/pulls/$number',
    path: '/pulls/$number',
    getParentRoute: () => GithubOwnerRepoRoute,
  } as any)
const GithubOwnerRepoIssuesNumberRoute =
  GithubOwnerRepoIssuesNumberRouteImport.update({
    id: '/issues/$number',
    path: '/issues/$number',
    getParentRoute: () => GithubOwnerRepoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/board': typeof BoardRoute
  '/github': typeof GithubRouteWithChildren
  '/login': typeof LoginRoute
  '/pipelines': typeof PipelinesRoute
  '/queue': typeof QueueRoute
  '/repositories': typeof RepositoriesRoute
  '/sessions-v1': typeof SessionsV1Route
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/welcome': typeof WelcomeRoute
  '/sessions-v1/$id': typeof SessionsV1IdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/settings/plugins/$pluginId': typeof SettingsPluginsPluginIdRoute
  '/github/$owner/$repo': typeof GithubOwnerRepoRouteWithChildren
  '/github/$owner/$repo/issues/$number': typeof GithubOwnerRepoIssuesNumberRoute
  '/github/$owner/$repo/pulls/$number': typeof GithubOwnerRepoPullsNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/board': typeof BoardRoute
  '/github': typeof GithubRouteWithChildren
  '/login': typeof LoginRoute
  '/pipelines': typeof PipelinesRoute
  '/queue': typeof QueueRoute
  '/repositories': typeof RepositoriesRoute
  '/sessions-v1': typeof SessionsV1Route
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/welcome': typeof WelcomeRoute
  '/sessions-v1/$id': typeof SessionsV1IdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/settings/plugins/$pluginId': typeof SettingsPluginsPluginIdRoute
  '/github/$owner/$repo': typeof GithubOwnerRepoRouteWithChildren
  '/github/$owner/$repo/issues/$number': typeof GithubOwnerRepoIssuesNumberRoute
  '/github/$owner/$repo/pulls/$number': typeof GithubOwnerRepoPullsNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/board': typeof BoardRoute
  '/github': typeof GithubRouteWithChildren
  '/login': typeof LoginRoute
  '/pipelines': typeof PipelinesRoute
  '/queue': typeof QueueRoute
  '/repositories': typeof RepositoriesRoute
  '/sessions-v1': typeof SessionsV1Route
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/welcome': typeof WelcomeRoute
  '/sessions-v1_/$id': typeof SessionsV1IdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/settings_/plugins/$pluginId': typeof SettingsPluginsPluginIdRoute
  '/github/$owner/$repo': typeof GithubOwnerRepoRouteWithChildren
  '/github/$owner/$repo/issues/$number': typeof GithubOwnerRepoIssuesNumberRoute
  '/github/$owner/$repo/pulls/$number': typeof GithubOwnerRepoPullsNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/board'
    | '/github'
    | '/login'
    | '/pipelines'
    | '/queue'
    | '/repositories'
    | '/sessions-v1'
    | '/settings'
    | '/templates'
    | '/welcome'
    | '/sessions-v1/$id'
    | '/sessions/$id'
    | '/settings/plugins/$pluginId'
    | '/github/$owner/$repo'
    | '/github/$owner/$repo/issues/$number'
    | '/github/$owner/$repo/pulls/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/board'
    | '/github'
    | '/login'
    | '/pipelines'
    | '/queue'
    | '/repositories'
    | '/sessions-v1'
    | '/settings'
    | '/templates'
    | '/welcome'
    | '/sessions-v1/$id'
    | '/sessions/$id'
    | '/settings/plugins/$pluginId'
    | '/github/$owner/$repo'
    | '/github/$owner/$repo/issues/$number'
    | '/github/$owner/$repo/pulls/$number'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/board'
    | '/github'
    | '/login'
    | '/pipelines'
    | '/queue'
    | '/repositories'
    | '/sessions-v1'
    | '/settings'
    | '/templates'
    | '/welcome'
    | '/sessions-v1_/$id'
    | '/sessions/$id'
    | '/settings_/plugins/$pluginId'
    | '/github/$owner/$repo'
    | '/github/$owner/$repo/issues/$number'
    | '/github/$owner/$repo/pulls/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BoardRoute: typeof BoardRoute
  GithubRoute: typeof GithubRouteWithChildren
  LoginRoute: typeof LoginRoute
  PipelinesRoute: typeof PipelinesRoute
  QueueRoute: typeof QueueRoute
  RepositoriesRoute: typeof RepositoriesRoute
  SessionsV1Route: typeof SessionsV1Route
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  WelcomeRoute: typeof WelcomeRoute
  SessionsV1IdRoute: typeof SessionsV1IdRoute
  SessionsIdRoute: typeof SessionsIdRoute
  SettingsPluginsPluginIdRoute: typeof SettingsPluginsPluginIdRoute
}

declare module '@tanstack/vue-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions-v1': {
      id: '/sessions-v1'
      path: '/sessions-v1'
      fullPath: '/sessions-v1'
      preLoaderRoute: typeof SessionsV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions-v1_/$id': {
      id: '/sessions-v1_/$id'
      path: '/sessions-v1/$id'
      fullPath: '/sessions-v1/$id'
      preLoaderRoute: typeof SessionsV1IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/plugins/$pluginId': {
      id: '/settings_/plugins/$pluginId'
      path: '/settings/plugins/$pluginId'
      fullPath: '/settings/plugins/$pluginId'
      preLoaderRoute: typeof SettingsPluginsPluginIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github/$owner/$repo/pulls/$number': {
      id: '/github/$owner/$repo/pulls/$number'
      path: '/pulls/$number'
      fullPath: '/github/$owner/$repo/pulls/$number'
      preLoaderRoute: typeof GithubOwnerRepoPullsNumberRouteImport
      parentRoute: typeof GithubOwnerRepoRoute
    }
    '/github/$owner/$repo/issues/$number': {
      id: '/github/$owner/$repo/issues/$number'
      path: '/issues/$number'
      fullPath: '/github/$owner/$repo/issues/$number'
      preLoaderRoute: typeof GithubOwnerRepoIssuesNumberRouteImport
      parentRoute: typeof GithubOwnerRepoRoute
    }
    '/github/$owner/$repo': {
      id: '/github/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/github/$owner/$repo'
      preLoaderRoute: typeof GithubOwnerRepoRouteImport
      parentRoute: typeof GithubRoute
    }
  }
}

interface GithubOwnerRepoRouteChildren {
  GithubOwnerRepoIssuesNumberRoute: typeof GithubOwnerRepoIssuesNumberRoute
  GithubOwnerRepoPullsNumberRoute: typeof GithubOwnerRepoPullsNumberRoute
}

const GithubOwnerRepoRouteChildren: GithubOwnerRepoRouteChildren = {
  GithubOwnerRepoIssuesNumberRoute: GithubOwnerRepoIssuesNumberRoute,
  GithubOwnerRepoPullsNumberRoute: GithubOwnerRepoPullsNumberRoute,
}

const GithubOwnerRepoRouteWithChildren =
  GithubOwnerRepoRoute._addFileChildren(GithubOwnerRepoRouteChildren)

interface GithubRouteChildren {
  GithubOwnerRepoRoute: typeof GithubOwnerRepoRouteWithChildren
}

const GithubRouteChildren: GithubRouteChildren = {
  GithubOwnerRepoRoute: GithubOwnerRepoRouteWithChildren,
}

const GithubRouteWithChildren =
  GithubRoute._addFileChildren(GithubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BoardRoute: BoardRoute,
  GithubRoute: GithubRouteWithChildren,
  LoginRoute: LoginRoute,
  PipelinesRoute: PipelinesRoute,
  QueueRoute: QueueRoute,
  RepositoriesRoute: RepositoriesRoute,
  SessionsV1Route: SessionsV1Route,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  WelcomeRoute: WelcomeRoute,
  SessionsV1IdRoute: SessionsV1IdRoute,
  SessionsIdRoute: SessionsIdRoute,
  SettingsPluginsPluginIdRoute: SettingsPluginsPluginIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
