/**
 * `weave-fleet init <directory>` command implementation.
 * Scans a project directory, detects technologies, and generates
 * a project-level .opencode/weave-opencode.jsonc config.
 */

import { existsSync, mkdirSync, writeFileSync } from "fs";
import { resolve } from "path";
import { detectProject } from "./detect-project";
import { listInstalledSkills } from "./skill-catalog";
import {
  getProjectConfigDir,
  getProjectWeaveConfigPath,
} from "./config-paths";

export interface InitOptions {
  force?: boolean;
  dryRun?: boolean;
}

export interface InitResult {
  configPath: string;
  profile: ReturnType<typeof detectProject>;
  enabledSkills: string[];
  written: boolean;
}

/** Default agent-skill mapping rules: which agents get which skill categories */
const AGENT_SKILL_MAP: Record<string, string[]> = {
  tapestry: [
    "enforcing-csharp-standards",
    "enforcing-dotnet-testing",
    "verifying-release-builds",
  ],
  shuttle: ["enforcing-csharp-standards", "enforcing-dotnet-testing"],
  weft: ["reviewing-csharp-code"],
};

/**
 * Generate the JSONC config content with comments.
 */
function generateConfig(
  enabledSkills: string[],
  agentSkillMap: Record<string, string[]>
): string {
  const agents: Record<string, { skills: string[] }> = {};

  for (const [agent, candidateSkills] of Object.entries(agentSkillMap)) {
    const skills = candidateSkills.filter((s) => enabledSkills.includes(s));
    if (skills.length > 0) {
      agents[agent] = { skills };
    }
  }

  const config = { agents };
  const json = JSON.stringify(config, null, 2);

  return `// Generated by weave-fleet init — customize as needed.
// This is deep-merged with ~/.config/opencode/weave-opencode.jsonc
${json}
`;
}

/**
 * Run the init command.
 *
 * @param directory - The project directory to initialize
 * @param options - Init options (force, dryRun)
 * @returns The result of the init operation
 */
export function runInit(directory: string, options: InitOptions = {}): InitResult {
  const { force = false, dryRun = false } = options;
  const projectDir = resolve(directory);

  // Validate directory exists
  if (!existsSync(projectDir)) {
    throw new Error(`Directory does not exist: ${projectDir}`);
  }

  const configPath = getProjectWeaveConfigPath(projectDir);

  // Check if config already exists
  if (existsSync(configPath) && !force) {
    throw new Error(
      `Config already exists at ${configPath}. Use --force to overwrite.`
    );
  }

  // Detect project technologies
  const profile = detectProject(projectDir);

  // Get installed skills and intersect with suggestions
  const installed = listInstalledSkills();
  const installedNames = new Set(installed.map((s) => s.name));
  const enabledSkills = profile.suggestedSkills.filter((s) =>
    installedNames.has(s)
  );

  // Generate config content
  const configContent = generateConfig(enabledSkills, AGENT_SKILL_MAP);

  // Write unless dry-run
  if (!dryRun) {
    const configDir = getProjectConfigDir(projectDir);
    mkdirSync(configDir, { recursive: true });
    writeFileSync(configPath, configContent, "utf-8");
  }

  return {
    configPath,
    profile,
    enabledSkills,
    written: !dryRun,
  };
}
