#!/usr/bin/env bash
# deploy/provision-fleet-env.sh — Securely provision /opt/fleet/data/fleet.env on the remote host.
#
# Shared by bootstrap.sh and deploy.sh so runtime config is refreshed from environment
# variables on every deploy, not only during initial infrastructure bootstrap.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

log() { echo "[fleet-env] $*"; }

require_single_line() {
  local name="$1" value="$2"
  case "$value" in
    *$'\n'*|*$'\r'*)
      echo "[fleet-env] ERROR: $name must not contain CR/LF characters" >&2
      exit 1
      ;;
  esac
}

ssh_remote() {
  # shellcheck disable=SC2086
  ssh ${SSH_OPTS:-} "$FLEET_HOST" "$@"
}

scp_to_remote() {
  local src="$1" dst="$2"
  # shellcheck disable=SC2086
  scp ${SSH_OPTS:-} "$src" "$FLEET_HOST:$dst"
}

: "${FLEET_HOST:?FLEET_HOST must be set}"
: "${FLEET_DOMAIN:?FLEET_DOMAIN must be set}"
: "${Fleet__Auth__Authority:?Fleet__Auth__Authority must be set}"
: "${Fleet__Auth__ClientId:?Fleet__Auth__ClientId must be set}"
: "${Fleet__Auth__ClientSecret:?Fleet__Auth__ClientSecret must be set}"

require_single_line "FLEET_DOMAIN" "$FLEET_DOMAIN"
require_single_line "Fleet__Auth__Authority" "$Fleet__Auth__Authority"
require_single_line "Fleet__Auth__ClientId" "$Fleet__Auth__ClientId"
require_single_line "Fleet__Auth__ClientSecret" "$Fleet__Auth__ClientSecret"

log "Provisioning fleet.env..."

set +x

FLEET_ENV_TMP="$(mktemp)"
chmod 600 "$FLEET_ENV_TMP"

cleanup() {
  rm -f "$FLEET_ENV_TMP" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

cat <<'ENVEOF' > "$FLEET_ENV_TMP"
# Weave Fleet runtime configuration
# Generated by deployment automation — do not edit manually; re-run deploy/bootstrap to update
Fleet__Auth__Enabled=true
Fleet__Cloud__Enabled=true
Fleet__Cloud__WorkspaceRoot=/data/workspaces
Fleet__DataProtection__KeyPath=/opt/fleet/data/keys
Fleet__DatabasePath=/opt/fleet/data/weave-fleet.db
Fleet__AnalyticsDatabasePath=/opt/fleet/data/weave-fleet-analytics.db
ENVEOF

printf 'Fleet__Auth__Authority=%s\n'    "$Fleet__Auth__Authority"    >> "$FLEET_ENV_TMP"
printf 'Fleet__Auth__ClientId=%s\n'     "$Fleet__Auth__ClientId"     >> "$FLEET_ENV_TMP"
printf 'Fleet__Auth__ClientSecret=%s\n' "$Fleet__Auth__ClientSecret" >> "$FLEET_ENV_TMP"
printf 'Fleet__Auth__AllowedOrigins__0=%s\n' "https://$FLEET_DOMAIN" >> "$FLEET_ENV_TMP"

REMOTE_ENV_TMP="$(ssh ${SSH_OPTS:-} "$FLEET_HOST" "mktemp /home/\$(id -un)/fleet.env.XXXXXX")"
scp_to_remote "$FLEET_ENV_TMP" "$REMOTE_ENV_TMP"
ssh_remote "tmp_path='$REMOTE_ENV_TMP'; cleanup() { rm -f \"\$tmp_path\"; }; trap cleanup EXIT INT TERM; sudo install -m 600 -o fleet -g fleet \"\$tmp_path\" /opt/fleet/data/fleet.env"

log "fleet.env provisioned at /opt/fleet/data/fleet.env"
