/**
 * End-to-end smoke test for the CLI workflow.
 *
 * Exercises the full init → skill install → skill list → skill remove flow
 * using real filesystem operations in temp directories.
 */

import { tmpdir } from "os";
import { join } from "path";
import {
  mkdirSync,
  writeFileSync,
  rmSync,
  existsSync,
  readFileSync,
} from "fs";
import { randomUUID } from "crypto";
import { runInit } from "../init";
import {
  listInstalledSkills,
  parseJsonc,
  type WeaveConfig,
} from "../skill-catalog";
import { installSkill, removeSkill } from "../skill-installer";

describe("E2E smoke test", () => {
  let projectDir: string;
  let skillsDir: string;
  let configPath: string;

  beforeEach(() => {
    const id = randomUUID();
    projectDir = join(tmpdir(), `e2e-project-${id}`);
    skillsDir = join(tmpdir(), `e2e-skills-${id}`);
    configPath = join(tmpdir(), `e2e-config-${id}`, "weave-opencode.jsonc");

    mkdirSync(projectDir, { recursive: true });
    mkdirSync(skillsDir, { recursive: true });
    mkdirSync(join(tmpdir(), `e2e-config-${id}`), { recursive: true });
  });

  afterEach(() => {
    for (const dir of [
      projectDir,
      skillsDir,
      join(configPath, ".."),
    ]) {
      if (existsSync(dir)) {
        rmSync(dir, { recursive: true, force: true });
      }
    }
  });

  it("FullCLIWorkflow_InitThenInstallThenListThenRemove", async () => {
    // --- Step 1: Set up a C# project directory ---
    writeFileSync(join(projectDir, "MyApp.csproj"), "<Project></Project>");
    mkdirSync(join(projectDir, ".git"));

    // --- Step 2: Run init ---
    const initResult = runInit(projectDir);

    expect(initResult.written).toBe(true);
    expect(initResult.profile.languages).toContain("csharp");
    expect(initResult.profile.frameworks).toContain("dotnet");
    expect(initResult.profile.isGitRepo).toBe(true);
    expect(existsSync(initResult.configPath)).toBe(true);

    // Verify generated config is valid JSONC
    const configContent = readFileSync(initResult.configPath, "utf-8");
    expect(configContent).toContain("Generated by weave-fleet init");
    const parsed = parseJsonc(configContent) as WeaveConfig;
    expect(parsed).toBeDefined();

    // --- Step 3: Verify skill list is initially empty (in our isolated dir) ---
    const initialSkills = listInstalledSkills(skillsDir, configPath);
    expect(initialSkills).toHaveLength(0);

    // --- Step 4: Install a skill from a local file ---
    const skillContent = [
      "---",
      "name: test-e2e-skill",
      "description: A skill for E2E testing",
      "---",
      "",
      "# Test E2E Skill",
      "",
      "This is a test skill used in end-to-end testing.",
    ].join("\n");

    const localSkillPath = join(projectDir, "test-skill.md");
    writeFileSync(localSkillPath, skillContent);

    const installResult = await installSkill(localSkillPath, {
      skillsDir,
      configPath,
      agents: ["tapestry", "shuttle"],
    });

    expect(installResult.name).toBe("test-e2e-skill");
    expect(installResult.description).toBe("A skill for E2E testing");
    expect(existsSync(join(skillsDir, "test-e2e-skill", "SKILL.md"))).toBe(
      true
    );

    // --- Step 5: Verify skill list shows the installed skill ---
    const afterInstall = listInstalledSkills(skillsDir, configPath);
    expect(afterInstall).toHaveLength(1);
    expect(afterInstall[0].name).toBe("test-e2e-skill");
    expect(afterInstall[0].description).toBe("A skill for E2E testing");
    expect(afterInstall[0].assignedAgents).toContain("tapestry");
    expect(afterInstall[0].assignedAgents).toContain("shuttle");

    // --- Step 6: Verify agent config was written ---
    const agentConfig = parseJsonc(
      readFileSync(configPath, "utf-8")
    ) as WeaveConfig;
    expect(agentConfig.agents?.tapestry?.skills).toContain("test-e2e-skill");
    expect(agentConfig.agents?.shuttle?.skills).toContain("test-e2e-skill");

    // --- Step 7: Remove the skill ---
    removeSkill("test-e2e-skill", { skillsDir, configPath });

    expect(existsSync(join(skillsDir, "test-e2e-skill"))).toBe(false);

    // --- Step 8: Verify skill list is empty again ---
    const afterRemove = listInstalledSkills(skillsDir, configPath);
    expect(afterRemove).toHaveLength(0);

    // --- Step 9: Verify agent config was cleaned up ---
    const cleanedConfig = parseJsonc(
      readFileSync(configPath, "utf-8")
    ) as WeaveConfig;
    const tapestrySkills = cleanedConfig.agents?.tapestry?.skills ?? [];
    const shuttleSkills = cleanedConfig.agents?.shuttle?.skills ?? [];
    expect(tapestrySkills).not.toContain("test-e2e-skill");
    expect(shuttleSkills).not.toContain("test-e2e-skill");
  });

  it("InitThenReInitFails_ForceOverwrites", () => {
    writeFileSync(join(projectDir, "package.json"), "{}");
    writeFileSync(
      join(projectDir, "next.config.ts"),
      "export default {}"
    );

    // First init
    const result1 = runInit(projectDir);
    expect(result1.written).toBe(true);
    expect(result1.profile.frameworks).toContain("nextjs");

    // Second init should fail
    expect(() => runInit(projectDir)).toThrow("Config already exists");

    // Force should work
    const result2 = runInit(projectDir, { force: true });
    expect(result2.written).toBe(true);
  });

  it("InstallSameSkillTwiceFails_ForceOverwrites", async () => {
    const skillContent = [
      "---",
      "name: duplicate-test",
      "description: Testing duplicate install",
      "---",
      "# Duplicate Test",
    ].join("\n");

    const localPath = join(projectDir, "dup-skill.md");
    writeFileSync(localPath, skillContent);

    // First install
    await installSkill(localPath, { skillsDir, configPath });
    expect(existsSync(join(skillsDir, "duplicate-test", "SKILL.md"))).toBe(
      true
    );

    // Second install should fail
    await expect(
      installSkill(localPath, { skillsDir, configPath })
    ).rejects.toThrow("already installed");

    // Force should work
    const result = await installSkill(localPath, {
      skillsDir,
      configPath,
      force: true,
    });
    expect(result.name).toBe("duplicate-test");
  });
});
