import { tmpdir } from "os";
import { join } from "path";
import {
  mkdirSync,
  writeFileSync,
  rmSync,
  existsSync,
  readFileSync,
} from "fs";
import { randomUUID } from "crypto";
import { runInit } from "../init";
import { parseJsonc } from "../skill-catalog";

describe("runInit", () => {
  let testDir: string;
  let skillsDir: string;

  beforeEach(() => {
    testDir = join(tmpdir(), `init-test-${randomUUID()}`);
    mkdirSync(testDir, { recursive: true });

    // Create a mock skills directory with some skills
    skillsDir = join(tmpdir(), `skills-test-${randomUUID()}`);
    mkdirSync(skillsDir, { recursive: true });
  });

  afterEach(() => {
    for (const dir of [testDir, skillsDir]) {
      if (existsSync(dir)) {
        rmSync(dir, { recursive: true, force: true });
      }
    }
  });

  it("GeneratesConfigForCSharpProject", () => {
    // Set up a C# project
    writeFileSync(join(testDir, "MyApp.csproj"), "<Project></Project>");
    mkdirSync(join(testDir, ".git"));

    const result = runInit(testDir, { dryRun: true });

    expect(result.profile.languages).toContain("csharp");
    expect(result.profile.frameworks).toContain("dotnet");
    expect(result.profile.isGitRepo).toBe(true);
    expect(result.written).toBe(false);
    expect(result.configPath).toContain(".opencode/weave-opencode.jsonc");
  });

  it("WritesConfigFileWhenNotDryRun", () => {
    writeFileSync(join(testDir, "package.json"), "{}");

    const result = runInit(testDir);

    expect(result.written).toBe(true);
    expect(existsSync(result.configPath)).toBe(true);

    const content = readFileSync(result.configPath, "utf-8");
    // Should have the header comment
    expect(content).toContain("Generated by weave-fleet init");
    // Should be valid JSONC
    const parsed = parseJsonc(content);
    expect(parsed).toBeDefined();
  });

  it("ErrorsWhenConfigAlreadyExists", () => {
    writeFileSync(join(testDir, "package.json"), "{}");

    // First init
    runInit(testDir);

    // Second init should fail
    expect(() => runInit(testDir)).toThrow("Config already exists");
  });

  it("OverwritesWithForceFlag", () => {
    writeFileSync(join(testDir, "package.json"), "{}");

    // First init
    runInit(testDir);

    // Second init with --force should succeed
    const result = runInit(testDir, { force: true });
    expect(result.written).toBe(true);
  });

  it("ErrorsForNonExistentDirectory", () => {
    expect(() => runInit("/non/existent/path")).toThrow(
      "Directory does not exist"
    );
  });

  it("DryRunDoesNotWriteFile", () => {
    writeFileSync(join(testDir, "package.json"), "{}");

    const result = runInit(testDir, { dryRun: true });

    expect(result.written).toBe(false);
    expect(existsSync(result.configPath)).toBe(false);
  });

  it("CreatesOpencodeDirectory", () => {
    writeFileSync(join(testDir, "package.json"), "{}");

    runInit(testDir);

    expect(existsSync(join(testDir, ".opencode"))).toBe(true);
  });
});
